name: Run Unit Tests

on:
  push:
    branches:
      - main  # Ejecutar los tests en la rama principal
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # Puedes ajustar la versión de Python según tu proyecto

    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)/AdventuresInMinecraft-PC-master/MinecraftAgentFramework" >> $GITHUB_ENV

    - name: Run Unit Tests
      run: |
        python -m unittest discover -s AdventuresInMinecraft-PC-master/MinecraftAgentFramework/tests -p "*.py"
